### ISSUE TITLE
Gradle Dependency not pulling

### ISSUE THREAD

**Issue by VenomousInc** [michaelbull/rs-api#1]
The Jitpack seems to be missing the main Jar file, as I get:
> org.gradle.internal.resource.transport.http.HttpRequestException: Could not HEAD 'https://jitpack.io/com/github/michaelbull/rs-api/master/rs-api-master.jar'

I also tried to pull 1.0.0, I don't get any errors but it also doesn't pull anything.

**Comment by michaelbull** [comment]
Thanks, [v1.0.1](https://github.com/michaelbull/rs-api/releases/tag/1.0.1) should resolve this.
