### ISSUE TITLE
Player Information throws exception if skill is locked

### ISSUE THREAD

**Issue by jsnells1** [michaelbull/rs-api#4]
When trying to get player information from Hiscores, if a skill is locked like Invention, the level is 0 instead of 1. This throws an exception when I assume it shouldn't.

**Comment by michaelbull** [comment]
Ah, think this will be a case of changing [this line](https://github.com/michaelbull/rs-api/blob/master/src/main/java/com/github/michaelbull/rs/hiscores/Skill.java#L75). If you want to open a PR to change it that'd be appreciated, if not I can address this soon.

**Comment by jsnells1** [comment]
I'll try to get around to it. I just found the api and am getting used to it. It'll be a couple changes to convert the level from 0 to 1 and the experience from -1 to 0 but it looks like it can  all be done in that constructor.

EDIT: Nevermind, I see you check for experience. Would you want the level to stay as 0?
